### ISSUE TITLE
Any chance to see it updated to Angular Final? This chapter is out of date

### ISSUE THREAD

**Issue by luigidallavalle** [PacktPublishing/Mastering-Angular-2-Components#3]
Hi,
I followed the idea behind this chapter, but since I have and Angular2 + Webpack application, that uses Typescript, the solutions it's kind of unusable, although the principles are still valid.
Angular has reached its final version months ago, and google its aiming toward Webpack and Typescript.
Do you have any plans to update the chapter somehow?

Thanks in advance

**Comment by gaurav-packt** [comment]
Please reopen the issue if it still exists.
