### ISSUE TITLE
Unable to run the app on localhost

### ISSUE THREAD

**Issue by anteburazer** [PacktPublishing/Mastering-Angular-2-Components#4]
Hi

I installed all pre-requisites and all dependencies using `npm install` and `jspm install`.
After running `npm start` gulp does it's job and everything goes well but I don't know on which port the application is served. I tried several ports and also a default one (8080) described in [live-server docs](https://www.npmjs.com/package/live-server) but without luck.

Can you provide some help please?

Thanks

**Comment by AurobindoKar** [comment]
Hi,

I am closing the issue.
In case the issue still persists, feel free to reopen it.

Thanks
